# Generated by Django 4.1.3 on 2023-05-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_categories_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
